<?php

/**
 * @file
 * Ledger
 */

/****************************************************************
 * Drupal hooks
 * **************************************************************/

/**
 * Implements hook_permission().
 */
function ledger_permission() {
  return array(
    'administer ledger' => array(
      'title' => t('Administer Ledger'),
      'description' => t('Administer the ledger module settings.'),
      'restrict access' => TRUE,
    ),
  );
}

/***************************************************************
 * Access functions
 * *************************************************************/

/**
 * Generates granular entity permissions for use in hook_permission().
 *
 * @param $entity_type
 *   The entity type to define permissions for.
 *
 * @return array
 *   Returns an array of permissions for hook_permission().
 */
function ledger_entity_access_permissions($entity_type) {
  $entity_info = entity_get_info($entity_type);

  // Grab the entity label.
  $label = strtolower($entity_info['label plural']);

  // Generic create, view, and edit permissions.
  $permissions['create ' . $entity_type] = array(
    'title' => t('Create ledger @entity_type', array('@entity_type' => $label)),
  );
  $permissions['view all ' . $entity_type] = array(
    'title' => t('View all ledger @entity_type', array('@entity_type' => $label)),
    'restrict access' => TRUE,
  );
  $permissions['edit all ' . $entity_type] = array(
    'title' => t('Edit all ledger @entity_type', array('@entity_type' => $label)),
    'restrict access' => TRUE,
  );

  return $permissions;
}

/***************************************************************
 * Configuration functions
 * *************************************************************/

/**
 * Create ledger_value field.
 *
 * This function is not used by the ledger module itself, but is provided
 * for other ledger modules to use to add a value field to their entities.
 * See ledger_account_entry_configure_account_entry_types() for an example.
 *
 * @return
 *   Returns the field name.
 */
function ledger_configure_value_field() {

  // If the fraction field type isn't found, clear the Field cache.
  if (!field_info_field_types('fraction')) {
    field_cache_clear();
  }

  // Look up existing field information.
  $field_name = 'ledger_value';
  $field = field_info_field($field_name);

  // If the field doesn't exist, create it.
  if (empty($field)) {
    $field = array(
      'field_name' => $field_name,
      'type' => 'fraction',
      'cardinality' => 1,
      'translatable' => FALSE,
      'locked' => TRUE,
    );
    $field = field_create_field($field);
  }

  // Return the field name.
  return $field_name;
}

