<?php

/**
 * @file
 * Ledger Import
 */

/*************************************************************************
* Contrib hooks
*************************************************************************/

/**
* Implementation of hook_feeds_plugins().
*/
function ledger_import_feeds_plugins() {
  $info = array();
  
  // Account processor
  $info['FeedsLedgerAccountProcessor'] = array(
    'name' => 'Ledger Account Processor',
    'description' => 'Create Ledger Accounts from parsed content.',
    'handler' => array(
      'parent' => 'FeedsProcessor',
      'class' => 'FeedsLedgerAccountProcessor',
      'file' => 'FeedsLedgerAccountProcessor.inc',
      'path' => drupal_get_path('module', 'ledger_import') . '/plugins',
    ),
  );
  
  // Transaction processor
  $info['FeedsLedgerTransactionProcessor'] = array(
    'name' => 'Ledger Transaction Processor',
    'description' => 'Create Ledger Transactions from parsed content.',
    'handler' => array(
      'parent' => 'FeedsProcessor',
      'class' => 'FeedsLedgerTransactionProcessor',
      'file' => 'FeedsLedgerTransactionProcessor.inc',
      'path' => drupal_get_path('module', 'ledger_import') . '/plugins',
    ),
  );
  
  return $info;
}