<?php

/**
 * @file
 * Ledger
 */

/**
 * Implementation of hook_menu().
 */
function ledger_ui_menu() {
  $items = array();

  // Note: the following pages are defined by default Views:
  //   /ledger/accounts
  //   /ledger/transactions

  // Create an order.
  $items['ledger/accounts/add'] = array(
    'title' => 'Create an account',
    'description' => 'Create a new account.',
    'page callback' => 'ledger_ui_page_temp',
    'page arguments' => array(entity_get_controller('ledger_account')->create()),
    'access callback' => 'ledger_account_access',
    'access arguments' => array('create'),
    'weight' => 10,
  );

  $items['ledger/accounts/%ledger_account'] = array(
    'title callback' => 'ledger_ui_account_title',
    'title arguments' => array(2),
    'page callback' => 'ledger_ui_page_temp',
    'page arguments' => array(2),
    'access callback' => 'ledger_account_access',
    'access arguments' => array('view', 2),
  );
  $items['ledger/accounts/%ledger_account/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );
  $items['ledger/accounts/%ledger_account/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'ledger_ui_page_temp',
    'page arguments' => array(2),
    'access callback' => 'ledger_account_access',
    'access arguments' => array('update', 2),
    'type' => MENU_LOCAL_TASK,
    'weight' => -5,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );
  $items['ledger/accounts/%ledger_account/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'ledger_ui_page_temp',
    'page arguments' => array(2),
    'access callback' => 'ledger_account_access',
    'access arguments' => array('update', 2),
    'type' => MENU_LOCAL_TASK,
    'weight' => 20,
    'context' => MENU_CONTEXT_INLINE,
  );

  return $items;
}

/**
 * Implementation of hook_menu_local_tasks_alter().
 */
function ledger_ui_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  
  // Add action link 'ledger/accounts/add' on 'ledger/accounts'.
  if ($root_path == 'ledger/accounts') {
    $item = menu_get_item('ledger/accounts/add');
    if ($item['access']) {
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
    }
  }
}

/**
 * Implementation of hook_views_api().
 */
function ledger_ui_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'ledger_ui') . '/views',
  );
}

/**
 * Menu item title callback: returns an account name for it's pages.
 *
 * @param $account
 *   The account object as loaded via the URL wildcard.
 * @return
 *   The account name.
 */
function ledger_ui_account_title($account) {
  return $account->name;
}


function ledger_ui_page_temp($account) {
  dpm($account);
  return 'PAGE TEMP';
}