<?php

/**
 * @file
 * Ledger
 */

/**
 * Implementation of hook_menu().
 */
function ledger_ui_menu() {
  $items = array();
  
  $items['ledger'] = array(
    'title' => 'Ledger',
    'description' => 'Administer the ledger.',
    'page callback' => 'ledger_ui_dashboard',
    'access arguments' => array('administer ledger'),
  );
  
  // Note: the following pages are defined by default Views:
  //   /ledger/accounts
  //   /ledger/transactions

  // Create account
  $items['ledger/accounts/add'] = array(
    'title' => 'Create a ledger account',
    'description' => 'Create a new ledger account.',
    'page callback' => 'ledger_ui_account_form_wrapper',
    'page arguments' => array(entity_get_controller('ledger_account')->create()),
    'access callback' => 'ledger_account_access',
    'access arguments' => array('create'),
    'weight' => 10,
    'file' => 'ledger_ui.admin.account.inc',
  );
  
  // View account
  $items['ledger/accounts/%ledger_account'] = array(
    'title callback' => 'ledger_ui_account_title',
    'title arguments' => array(2),
    'page callback' => 'ledger_ui_page_temp',
    'page arguments' => array(2),
    'access callback' => 'ledger_account_access',
    'access arguments' => array('view', 2),
  );
  $items['ledger/accounts/%ledger_account/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );
  
  // Edit account
  $items['ledger/accounts/%ledger_account/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'ledger_ui_account_form_wrapper',
    'page arguments' => array(2),
    'access callback' => 'ledger_account_access',
    'access arguments' => array('update', 2),
    'type' => MENU_LOCAL_TASK,
    'weight' => -5,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
    'file' => 'ledger_ui.admin.account.inc',
  );
  
  // Delete account
  $items['ledger/accounts/%ledger_account/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'ledger_ui_page_temp',
    'page arguments' => array(2),
    'access callback' => 'ledger_account_access',
    'access arguments' => array('update', 2),
    'type' => MENU_LOCAL_TASK,
    'weight' => 20,
    'context' => MENU_CONTEXT_INLINE,
    'file' => 'ledger_ui.admin.account.inc',
  );
  
  // Create transaction
  $items['ledger/transactions/add'] = array(
    'title' => 'Record a ledger transaction',
    'description' => 'Record a new transaction in the ledger.',
    'page callback' => 'ledger_ui_page_temp',
    'page arguments' => array(entity_get_controller('ledger_transaction')->create()),
    'access callback' => 'ledger_transaction_access',
    'access arguments' => array('create'),
    'weight' => 10,
    'file' => 'ledger_ui.admin.transaction.inc',
  );
  
  // View transaction
  $items['ledger/transactions/%ledger_transaction'] = array(
    'title callback' => 'ledger_ui_transaction_title',
    'title arguments' => array(2),
    'page callback' => 'ledger_ui_page_temp',
    'page arguments' => array(2),
    'access callback' => 'ledger_transaction_access',
    'access arguments' => array('view', 2),
  );
  $items['ledger/transactions/%ledger_transaction/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );
  
  // Edit transaction
  $items['ledger/transactions/%ledger_transaction/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'ledger_ui_page_temp',
    'page arguments' => array(2),
    'access callback' => 'ledger_transaction_access',
    'access arguments' => array('update', 2),
    'type' => MENU_LOCAL_TASK,
    'weight' => -5,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
    'file' => 'ledger_ui.admin.transaction.inc',
  );
  
  // Delete transaction
  $items['ledger/transactions/%ledger_transaction/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'ledger_ui_page_temp',
    'page arguments' => array(2),
    'access callback' => 'ledger_transaction_access',
    'access arguments' => array('update', 2),
    'type' => MENU_LOCAL_TASK,
    'weight' => 20,
    'context' => MENU_CONTEXT_INLINE,
    'file' => 'ledger_ui.admin.transaction.inc',
  );

  return $items;
}

/**
 * Implementation of hook_menu_local_tasks_alter().
 */
function ledger_ui_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  
  // Add action link 'ledger/accounts/add' on 'ledger/accounts'.
  if ($root_path == 'ledger/accounts') {
    $item = menu_get_item('ledger/accounts/add');
    if ($item['access']) {
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
    }
  }
  
  // Add action link 'ledger/transactions/add' on 'ledger/transactions'.
  else if ($root_path == 'ledger/transactions') {
    $item = menu_get_item('ledger/transactions/add');
    if ($item['access']) {
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
    }
  }
}

/**
 * Implementation of hook_views_api().
 */
function ledger_ui_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'ledger_ui') . '/views',
  );
}

/**
 * Menu item title callback: returns an account name for it's pages.
 *
 * @param $account
 *   The account object as loaded via the URL wildcard.
 * @return
 *   The account name.
 */
function ledger_ui_account_title($account) {
  return $account->name;
}

/**
 * Menu item title callback: returns a transaction description for it's pages.
 *
 * @param $transaction
 *   The transaction object as loaded via the URL wildcard.
 * @return
 *   The transaction name.
 */
function ledger_ui_transaction_title($transaction) {
  return $account->description;
}

/**
 * Ledger dashboard page callback.
 */
function ledger_ui_dashboard() {
  
  $output = '';
  
  $account_types = array(
    'Asset',
    'Capital',
    'Income',
    'Expense',
    'Liability',
  );
  
  if (!empty($account_types)) {
    foreach ($account_types as $type => $name) {
      
      // Print the account type title
      $output .= '<strong>' . $name . '</strong>';
      
      $header = array(
        'header 1',
        'header 2',
        'header 3',
        'Weight',
      );
      for ($i=0;$i<5;$i++) {
        $rows[] = array(
          'data' => array(
            rand(1000, 99999),
            rand(1000, 99999),
            rand(1000, 99999),
            array(
              'data' => $i,
              'class' => array('account-weight', 'account-weight-'),
            ),
          ),
          'class' => array('draggable'),
        );
      }
  
      $output .= theme('table', array('header' => $header, 'rows' => $rows, 'attributes' => array('id' => 'ledger-table-' . $type)));
    }
  }
  
  /**
   * @todo This *should* be in the theme layer.
   */
  if (!empty($account_types)) {
    foreach ($account_types as $type => $name) {
      drupal_add_tabledrag('ledger-table-' . $type, 'order', 'sibling', 'account-weight', 'account-weight-' . $type);
    }
  }
  
  return $output;
}

function ledger_ui_page_temp($entity) {
  dpm($entity);
  return 'PAGE TEMP';
}