<?php

/**
 * @file
 * Ledger
 */

/***************************************************************
 * Drupal core hooks
 ***************************************************************/

/**
 * Implements hook_menu().
 */
function ledger_ui_menu() {
  $items = array();
  
  // Top level "Ledger" container.
  $items['admin/ledger'] = array(
    'title' => 'Ledger',
    'description' => 'Administer the accounts and transactions in the ledger.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
    'weight' => -7,
  );
  
  // Note: the following pages are defined by default Views:
  //   /admin/ledger/accounts
  //   /admin/ledger/accounts/%(/transactions)
  //   /admin/ledger/transactions

  // Create account
  $items['admin/ledger/accounts/add'] = array(
    'title' => 'Create a ledger account',
    'description' => 'Create a new ledger account.',
    'page callback' => 'ledger_ui_account_form_wrapper',
    'page arguments' => array(entity_get_controller('ledger_account')->create()),
    'access callback' => 'ledger_account_access',
    'access arguments' => array('create'),
    'weight' => 10,
    'file' => 'ledger_ui.admin.account.inc',
  );
  
  // Edit account
  $items['admin/ledger/accounts/%ledger_account/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'ledger_ui_account_form_wrapper',
    'page arguments' => array(3),
    'access callback' => 'ledger_account_access',
    'access arguments' => array('update', 3),
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
    'file' => 'ledger_ui.admin.account.inc',
  );
  
  // Delete account
  $items['admin/ledger/accounts/%ledger_account/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'ledger_ui_page_temp',
    'page arguments' => array(3),
    'access callback' => 'ledger_account_access',
    'access arguments' => array('update', 3),
    'type' => MENU_LOCAL_TASK,
    'weight' => 20,
    'context' => MENU_CONTEXT_INLINE,
    'file' => 'ledger_ui.admin.account.inc',
  );
  
  // Create transaction
  $items['admin/ledger/transactions/add'] = array(
    'title' => 'Record a ledger transaction',
    'description' => 'Record a new transaction in the ledger.',
    'page callback' => 'ledger_ui_transaction_form_wrapper',
    'page arguments' => array(entity_get_controller('ledger_transaction')->create()),
    'access callback' => 'ledger_transaction_access',
    'access arguments' => array('create'),
    'weight' => 10,
    'file' => 'ledger_ui.admin.transaction.inc',
  );
  
  // View transaction
  $items['admin/ledger/transactions/%ledger_transaction'] = array(
    'title callback' => 'ledger_ui_transaction_title',
    'title arguments' => array(3),
    'page callback' => 'ledger_ui_page_temp',
    'page arguments' => array(3),
    'access callback' => 'ledger_transaction_access',
    'access arguments' => array('view', 3),
  );
  $items['admin/ledger/transactions/%ledger_transaction/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 0,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );
  
  // Edit transaction
  $items['admin/ledger/transactions/%ledger_transaction/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'ledger_ui_transaction_form_wrapper',
    'page arguments' => array(3),
    'access callback' => 'ledger_transaction_access',
    'access arguments' => array('update', 3),
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
    'file' => 'ledger_ui.admin.transaction.inc',
  );
  
  // Delete transaction
  $items['admin/ledger/transactions/%ledger_transaction/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'ledger_ui_page_temp',
    'page arguments' => array(3),
    'access callback' => 'ledger_transaction_access',
    'access arguments' => array('update', 3),
    'type' => MENU_LOCAL_TASK,
    'weight' => 20,
    'context' => MENU_CONTEXT_INLINE,
    'file' => 'ledger_ui.admin.transaction.inc',
  );

  return $items;
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function ledger_ui_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  
  // Add action link 'ledger/accounts/add' on 'ledger/accounts'.
  if ($root_path == 'admin/ledger/accounts') {
    $item = menu_get_item('admin/ledger/accounts/add');
    if ($item['access']) {
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
    }
  }
  
  // Add action link 'ledger/transactions/add' on 'ledger/transactions'.
  else if ($root_path == 'admin/ledger/transactions' || $root_path == 'admin/ledger/accounts/%') {
    $item = menu_get_item('admin/ledger/transactions/add');
    if ($item['access']) {
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
    }
  }
}

/***************************************************************
 * Views hooks
 ***************************************************************/

/**
 * Implements hook_views_api().
 */
function ledger_ui_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'ledger_ui') . '/views',
  );
}

/***************************************************************
 * Menu item title callbacks
 ***************************************************************/

/**
 * Menu item title callback: returns an account name for it's pages.
 *
 * @param $account
 *   The account object as loaded via the URL wildcard.
 * @return
 *   The account name.
 */
function ledger_ui_account_title($account) {
  return $account->name;
}

/**
 * Menu item title callback: returns a transaction description for it's pages.
 *
 * @param $transaction
 *   The transaction object as loaded via the URL wildcard.
 * @return
 *   The transaction name.
 */
function ledger_ui_transaction_title($transaction) {
  return $transaction->description;
}

function ledger_ui_page_temp($entity) {
  dpm($entity);
  return 'PAGE TEMP';
}