<?php

/**
 * @file
 * Ledger Import GnuCash
 */

/*************************************************************************
* Contrib hooks
*************************************************************************/

/**
 * Implementation of hook_ctools_plugin_api().
 */
function ledger_import_gnucash_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == "feeds" && $api == "feeds_importer_default") {
    return array("version" => 1);
  }
}


/**
* Implementation of hook_feeds_plugins().
*/
function ledger_import_gnucash_feeds_plugins() {
  $info = array();
  
  // Account processor
  $info['FeedsLedgerGnuCashAccountProcessor'] = array(
    'name' => 'Ledger GnuCash Account Processor',
    'description' => 'Create Ledger Accounts from a GnuCash file.',
    'handler' => array(
      'parent' => 'FeedsLedgerAccountProcessor',
      'class' => 'FeedsLedgerGnuCashAccountProcessor',
      'file' => 'FeedsLedgerGnuCashAccountProcessor.inc',
      'path' => drupal_get_path('module', 'ledger_import_gnucash') . '/plugins',
    ),
  );
  
  return $info;
}

/**
 * Implementation of hook_feeds_importer_default().
 */
function ledger_import_gnucash_feeds_importer_default() {
  $export = array();
  
  // Load up the feed definitions.
  $importers = array(
    'ledger_import_gnucash_accounts',  // GnuCash Accounts import
  );
  if (!empty($importers)) {
    foreach ($importers as $importer) {
      require_once drupal_get_path('module', 'ledger_import_gnucash') . '/' . $importer . '.inc';
      if (!empty($feeds_importer)) {
        $export[$importer] = $feeds_importer;
      }
    }
  }
  
  return $export;
}