<?php

/**
 * @file
 * Ledger Period install
 */

/**
 * Implements hook_uninstall().
 */
function ledger_period_uninstall() {
  variable_del('ledger_period_sign_reverse');
  variable_del('ledger_period_balance_calculate');
}

/**
 * Implements hook_enable().
 */
function ledger_period_enable() {

  // Add Balance fields to account and account entry bundles.
  ledger_period_configure_account_types();
  ledger_period_configure_account_entry_types();
}

