<?php

/**
 * @file
 * Contains ledger_transaction.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ledger_transaction_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ledger_transaction module.
    case 'help.page.ledger_transaction':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides the Ledger Transaction log type.') . '</p>';
      return $output;

    default:
  }
}
