<?php

/**
 * @file
 * Ledger
 */

/***************************************************************
 * Drupal core hooks
 * *************************************************************/

/**
 * Implements hook_menu().
 */
function ledger_ui_menu() {
  $items = array();

  // Top level "Ledger" container.
  $items['ledger'] = array(
    'title' => 'Ledger',
    'description' => 'Manage books, accounts, and transactions.',
    'page callback' => 'ledger_ui_page_callback',
    'access arguments' => array('access administration pages'),
  );

  // Ledger Settings container
  $items['admin/config/ledger'] = array(
    'title' => 'Ledger',
    'description' => 'Administer ledger settings',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
  );

  return $items;
}

/***************************************************************
 * Page callbacks
 * *************************************************************/

/**
 * Page callback for the root /ledger patch.
 */
function ledger_ui_page_callback() {

  // Just a placeholder at the moment...
  $output = '';
  return $output;
}
