<?php

/**
 * @file
 * Ledger
 */

/***************************************************************
 * Drupal core hooks
 * *************************************************************/

/**
 * Implements hook_menu().
 */
function ledger_ui_menu() {
  $items = array();

  // Ledger Settings container
  $items['admin/config/ledger'] = array(
    'title' => 'Ledger',
    'description' => 'Administer ledger settings',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer ledger'),
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
  );

  return $items;
}

